### PR TITLE
Chef 11.18.0 Release

### PR DESCRIPTION
**Pull request by jdmundrawala**
cc @opscode/client-engineers

### CODE REVIEW

**Comment by tyler-ball** [comment]
@jdmundrawala Why did all the ChefDK stuff go away?  Does it have its own omnibus?

**Comment by jdmundrawala** [comment]
@tyler-ball it was causing problems, and we're not building chefdk off that branch anyway.

**Comment by lamont-granquist** [comment]
that's probably going to create merge conflicts in the future.

but i'm more and more convinced that we need to abandon this branch and get to the point of building chef-11 off of master.

**Comment by jdmundrawala** [comment]
The easiest thing will be to abandon this branch. This is using omnibus 3 and we've already done the work to change to omnibus 4, just need to make some tweaks to get chef 11 to build off that.

**Comment by lamont-granquist** [comment]
Biggest tweak would be disabling appbundling for chef < 11 which will be annoying, I'd vote that we just start appbundling chef-11 and declare it the way of the future.

**Pull request merged**
